**HANDLING IMBALANCED DATASETS**

- A Dataset with Unequal Class distribution

In [2]:
# Importing the Dependencies
import pandas as pd
import numpy as np

In [4]:
# Loading The Dataset to DataFrame
#credit_card_data=pd.read_csv('/content/credit_data.csv')

In [ ]:
# Checking the Distribution of Two Classes
credit_card_data['Class'].value_counts()

Class
0.0    3970
1.0       2
Name: count, dtype: int64

This is The Highly Imbalanced Dataset

0 --> Legit Transaction

1 --> Fradulent Transaction

In [ ]:
# Seperating the Data into two Classes
legit=credit_card_data[credit_card_data.Class==0]
fraud=credit_card_data[credit_card_data.Class==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(3970, 31)
(2, 31)

USING UNDER-SAMPLING TO HANDLE IMBALANCED DATA

-Undersampling is a data preprocessing technique used to balance imbalanced datasets in machine learning by reducing the number of samples in the majority class.

Now Building A Dataset Containing Similar Distribution of Legit & Fraudulent transactions

In [ ]:
legit_sample = legit.sample(n=492)

In [ ]:
legit_sample.shape

(492, 31)

Now Concatenate The Two DataFrames

In [ ]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)


axis=0 --> rowise concatenation

axis=1 --> columnwise concatenation

NOW THE NEW_DATASET IS EVENLY DISTRIBUTED

In [ ]:
# CHECKING THE NEW BALANCED DATASET
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
943,715,1.090820,-0.167031,0.350139,0.695740,-0.378402,-0.168184,-0.035248,0.005667,0.191769,...,-0.161932,-0.452659,-0.098339,0.050589,0.451644,0.264640,-0.037335,0.010801,69.97,0.0
3270,2820,-1.031687,0.464985,1.199978,-2.090495,-0.256690,-0.460438,0.119366,0.230882,1.666532,...,0.153282,0.647394,-0.343316,-0.433819,0.307043,-0.734760,-0.380361,-0.170009,0.90,0.0
2529,2095,-0.444487,0.576852,1.083307,-2.195446,0.372585,-0.720494,0.958912,-0.128664,0.646677,...,0.133831,0.739895,-0.273164,0.009800,-0.046555,-0.825379,0.248235,-0.028375,1.00,0.0
3218,2793,-3.168768,3.200173,-1.325055,0.410851,-0.390977,-1.368632,0.645542,0.098107,1.649373,...,-0.297982,0.549115,0.278475,0.356350,-0.293033,-0.559228,-0.449741,-0.787396,1.51,0.0
1957,1507,1.245032,-0.004197,0.288187,0.728763,-0.340890,-0.408937,-0.044149,-0.081308,0.562004,...,-0.264452,-0.625041,-0.059435,-0.118993,0.507177,0.302109,-0.028171,0.008849,19.55,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1777,1378,1.209728,0.579323,0.069218,2.513966,0.012613,-0.892993,0.443578,-0.172664,-0.752470,...,-0.032352,-0.231148,-0.088664,0.329878,0.658410,0.074455,-0.054534,0.007349,12.33,0.0
3358,2908,-0.341842,0.687529,0.735795,-2.286992,0.823709,-0.539584,1.121136,-0.286772,0.791590,...,0.040204,0.566474,-0.377761,-0.743524,0.133642,-0.759856,0.258387,-0.024239,1.00,0.0
3252,2806,-0.678299,0.754147,1.064098,-2.203174,0.215236,-0.855713,0.947868,-0.125218,0.836526,...,0.117266,0.748106,-0.234694,0.209229,-0.025926,-0.833350,0.352731,0.033568,1.00,0.0
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0